### ISSUE TITLE
Error while trying Flow - D3/Sankey

### ISSUE THREAD

**Issue by softwareklinic** [QXIP/Qbana#3]
While trying out the D3/Sankey flow --- I'm getting below error in Qiana

```
... 10 more
```

[2015-11-15 19:18:48,160][DEBUG][action.search.type       ] [Lunatica] [logstash-2015.11.16][0], node[s-rdx2QkR2CFymOgJCD7Bw], [P], v[2], s[STARTED], a[id=wvT6p2iUQhu7Cby_O8V22Q]: Failed to execute [org.elasticsearch.action.search.SearchRequest@605a8ede] lastShard [true]
RemoteTransportException[[Lunatica][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"facets":{"src_terms":{"terms":{"field":"source","size":20,"exclude":[]},"facet_filter":{"fquery":{"query":{"filtered":{"query":{"bool":{"should":[{"query_string":{"query":"_"}}]}},"filter":{"bool":{"must":[{"match_all":{}},{"exists":{"field":"source"}}]}}}}}}},"dst_terms":{"terms":{"field":"target","size":20,"exclude":[]},"facet_filter":{"fquery":{"query":{"filtered":{"query":{"bool":{"should":[{"query_string":{"query":"_"}}]}},"filter":{"bool":{"must":[{"match_all":{}},{"exists":{"field":"target"}}]}}}}}}}},"size":0}]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]];
Caused by: SearchParseException[failed to parse search source [{"facets":{"src_terms":{"terms":{"field":"source","size":20,"exclude":[]},"facet_filter":{"fquery":{"query":{"filtered":{"query":{"bool":{"should":[{"query_string":{"query":"_"}}]}},"filter":{"bool":{"must":[{"match_all":{}},{"exists":{"field":"source"}}]}}}}}}},"dst_terms":{"terms":{"field":"target","size":20,"exclude":[]},"facet_filter":{"fquery":{"query":{"filtered":{"query":{"bool":{"should":[{"query_string":{"query":"_"}}]}},"filter":{"bool":{"must":[{"match_all":{}},{"exists":{"field":"target"}}]}}}}}}}},"size":0}]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]];
    at org.elasticsearch.search.SearchService.parseSource(SearchService.java:860)
    at org.elasticsearch.search.SearchService.createContext(SearchService.java:663)
    at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:632)
    at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:374)
    at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
    at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
    at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: SearchParseException[failed to parse search source. unknown search element [facets]]
    at org.elasticsearch.search.SearchService.parseSource(SearchService.java:841)

**Comment by lmangani** [comment]
Hi @softwareklinic Kibana3/Qbana only supports facets and they were removed in ES 2.x

**Comment by softwareklinic** [comment]
Can I use old version of elastic search and any plans for updating qbana for latest Es

Regards,
Keyur

On Nov 25, 2015, at 4:18 PM, Lorenzo Mangani <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @softwareklinichttps://github.com/softwareklinic Kibana3/Qbana only supports facets and they were removed in ES 2.x

**Comment by lmangani** [comment]
Should work fine up to 1.7 - Integrating full aggs mode would be fun, but not likely unless others join the effort. Let's keep this open in case anyone wants to step forward and keep the old Kibana3/Qbana alive?

**Comment by softwareklinic** [comment]
Yeah - also I want to explore opportunity to see if we can have Sanket diagram in kibana - can some of the code be ported to kibana for flow, heat map etc.

Regards,
Keyur

On Nov 25, 2015, at 6:58 PM, Lorenzo Mangani <notifications@github.com<mailto:notifications@github.com>> wrote:

It would be fun, but not likely unless others join the effort. Let's keep this open in case anyone wants to step forward and keep the old Kibana3/Qbana alive?

**Comment by lmangani** [comment]
The main issue is current Kibana lacking the natural space for such extensions, but things are improving fast and soon it might be possible again, who knows. This is why QBana was forked. Porting the widgets is trivial, mapping the data a bit less.

**Comment by mroe1234** [comment]
I just started using Qbana with our ES installation.  This looks like a great project but we are going to be upgrading our ES cluster to 2.0 very soon.  I saw some mention in this issue that ES 2.0 will break compatibility with with Qbana.  Is this true and are there plans to support 2.0 in the near future?

**Comment by lmangani** [comment]
@mroe1234 unfortunately we do not have resources to support 2.x (unless someone wants to co-sponsor the effort) and full aggregations in QBana replacing facets. This being said, Kibana5 is promising to bring back some of the missing features and we will push our contributions there eventually.
